project:
  type: book

book:
  title: "Data Analysis Test"
  page-navigation: true

  page-footer:
    left: |
      The test was written by Lothar Rojas (April, 2023).
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  sidebar:
    title: "Data Analysis Test"
    background: "#EFF2F4"
    logo: "images/logo.png"
    align: center
    tools:
      - icon: code-square
        href: https://github.com/crispydoggo/LSE_RA_LRojas
        text: "Source Code"

  chapters:
    - index.qmd
    - exercise_1.qmd
    - exercise_2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: litera
    code-fold: true
  pdf:
    documentclass: scrreprt

editor: visual

