project:
  type: book

book:
  title: "Data Analysis Test"
  reader-mode: true

  page-footer:
    left: |
      The test was written by Lothar Rojas (April, 2023).
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  sidebar:
    background: "#EFF2F4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: code-square
        href: https://github.com/crispydoggo/LSE_RA_LRojas
        text: "Source Code"

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [litera, theme.scss]
  pdf:
    documentclass: scrreprt

editor: visual

